# Build Zotero plugin.

name: Build Zotero OCR

on:
  push:
    # branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]
  # schedule:
  #  - cron: '21 12 * * 0'

jobs:
  build-plugin:
    name: Build Zotero OCR plugin
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup git
        run: git config --global user.email "ci@example.com" && git config --global user.name "GitHub CI"

      - name: Run build
        run: ./release.sh $(git describe --tags || echo ci-test)-$(date -I) && cp -a build/*.xpi .

      - uses: actions/upload-artifact@v4
        with:
          name: Zotero OCR plugin (zipped)
          path: "*.xpi"
